# Generated by Django 3.0.5 on 2020-05-05 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='infromation',
            new_name='informations',
        ),
    ]
