# Generated by Django 3.0.5 on 2020-05-08 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20200507_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='about',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL),
        ),
    ]
