# Generated by Django 3.0.5 on 2020-05-08 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_person_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userclub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(default=False, max_length=50)),
                ('tag', models.CharField(default=False, max_length=10)),
                ('site_web', models.CharField(default=False, max_length=200)),
                ('email', models.CharField(default=False, max_length=100)),
                ('about', models.TextField(default=False)),
                ('create', models.DateField(auto_now_add=True, null=True)),
                ('userclub', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='personA', to='api.Person')),
            ],
        ),
    ]
